"""The architecture diagram, generated from the Helm chart rather than drawn.

A hand-drawn architecture diagram is wrong the day after it is committed. This
one is derived from the Helm chart given by ``CLOUDPROBE_CHART`` — the same
``values.yaml`` that decides what is actually deployed — so regenerating it is
the only way it changes, and drift is impossible.

Only secret **names** are read (from template filenames). No secret value is
opened, let alone rendered.
"""

from __future__ import annotations

import os
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml  # type: ignore[import-untyped]
from opscore.errors import ConfigError, NotFoundError

CHART_VAR = "CLOUDPROBE_CHART"
"""Where the Helm chart lives. There is no default: the original was an absolute
path into one person's home directory, which is the clearest possible way for a
tool to work on exactly one machine."""


def resolve_chart(chart_dir: Path | None = None) -> Path:
    """The chart to read, or a refusal naming the variable that fixes it.

    Read from the environment **at call time**, not bound at import: a module
    constant evaluated when the module loads cannot see a variable the entry
    point sets afterwards, and the tool then looks configurable while being
    fixed. That failure is already on this repository's record.

    Every caller goes through here, which is the other half. `load()` used to
    resolve the default and `render()` did not, so the same command read a real
    chart and then wrote a document that called it `<chart>` — a report that
    disagreed with the work it had just done.
    """
    resolved = chart_dir or (Path(os.environ[CHART_VAR]) if os.environ.get(CHART_VAR) else None)
    if resolved is None:
        raise ConfigError(
            f"no Helm chart: set {CHART_VAR} or pass --chart",
            detail="the topology is read from the chart; there is nothing sensible to assume",
        )
    return resolved
DEFAULT_VALUES = "values.yaml"
MARKER = "AUTO-GENERATED by `cloudprobe k8s-diagram`"


@dataclass
class Chart:
    """What the chart says is deployed."""

    deployments: list[str] = field(default_factory=list)
    hosts: dict[str, list[tuple[str, str]]] = field(default_factory=dict)
    """host → [(path, backend service)]"""

    secrets: list[str] = field(default_factory=list)

    def as_dict(self) -> dict[str, Any]:
        return {
            "deployments": self.deployments,
            "hosts": {h: [{"path": p, "service": s} for p, s in r] for h, r in self.hosts.items()},
            "secrets": self.secrets,
        }


def load(chart_dir: Path | None = None, values_name: str = DEFAULT_VALUES) -> Chart:
    """Read the chart's ingress rules, deployment list and secret names.

    Resolved at call time from `CLOUDPROBE_CHART` when not given. There is no
    default to guess: the original was an absolute path into one person's home
    directory, which is the clearest possible way for a tool to work on exactly
    one machine.
    """
    chart_dir = resolve_chart(chart_dir)
    values_file = chart_dir / values_name
    if not values_file.is_file():
        raise NotFoundError(f"values file not found: {values_file}")

    values = yaml.safe_load(values_file.read_text(encoding="utf-8")) or {}

    deployments = [d for d in (values.get("deployments") or []) if isinstance(d, str)]

    hosts: dict[str, list[tuple[str, str]]] = {}
    ingress = values.get("ingress")
    rules = ingress.get("hosts", []) if isinstance(ingress, dict) else []
    for rule in rules or []:
        if not isinstance(rule, dict):
            continue
        host = str(rule.get("host", "?"))
        for path_rule in rule.get("paths") or []:
            if not isinstance(path_rule, dict):
                continue
            service = ((path_rule.get("backend") or {}).get("service") or {}).get("name", "?")
            hosts.setdefault(host, []).append((str(path_rule.get("path", "?")), str(service)))

    templates = chart_dir / "templates"
    secrets = sorted(p.stem for p in templates.glob("*secret*.yaml")) if templates.is_dir() else []

    return Chart(deployments=deployments, hosts=hosts, secrets=secrets)


def _node_id(name: str) -> str:
    """Mermaid node ids cannot carry hyphens or dots."""
    return name.replace("-", "_").replace(".", "_")


def _chart_label(chart_dir: Path | None) -> str:
    """The chart's name for the diagram header, or a placeholder."""
    return chart_dir.name if chart_dir else "<chart>"


def chart_commit(chart_dir: Path | None) -> str | None:
    """The commit the chart was at when it was read, if it is in a git repository.

    A generated document that names a source path is a citation, and a path is
    only true against one revision — without the commit a reader cannot tell
    "this moved" from "this was always wrong". The generator is the one thing
    that knows the answer for certain, since it is holding the file, so it
    stamps it rather than leaving a human to guess later.

    Returns None outside a repository, which is a real case (an unpacked chart)
    and must read as *unknown*, not as an invented value.
    """
    if chart_dir is None or not chart_dir.exists():
        return None
    try:
        result = subprocess.run(
            ["git", "-C", str(chart_dir), "log", "-1", "--format=%h %cs", "--", "."],
            capture_output=True,
            text=True,
            timeout=10,
            check=False,
        )
    except (OSError, subprocess.SubprocessError):  # pragma: no cover - environment
        return None
    return result.stdout.strip() or None


def render(chart: Chart, *, chart_dir: Path | None, values_name: str) -> str:
    """Render the chart as a Mermaid diagram."""
    lines = [
        "# Kubernetes architecture",
        "",
        f"> {MARKER} from `{_chart_label(chart_dir)}/{values_name}`"
        + (f" @{stamp}" if (stamp := chart_commit(chart_dir)) else " (revision unknown)")
        + " — do not hand-edit.",
        "",
        "Request flow: **Cloudflare → GCP HTTPS load balancer → GKE**. Cloudflare",
        "owns the domain rules and edge blocking; the chart below owns everything",
        "from the load balancer inwards.",
        "",
        "```mermaid",
        "graph LR",
        "  CF[Cloudflare edge]",
        "  LB[GCP HTTPS LB]",
        "  CF --> LB",
    ]

    for host, routes in sorted(chart.hosts.items()):
        host_id = _node_id(host)
        lines.append(f'  {host_id}["{host}"]')
        lines.append(f"  LB --> {host_id}")
        for path, service in routes:
            service_id = _node_id(service)
            lines.append(f'  {host_id} -- "{path}" --> {service_id}["{service}"]')

    routed = {service for routes in chart.hosts.values() for _, service in routes}
    unrouted = [d for d in chart.deployments if d not in routed]
    if unrouted:
        lines.append("  subgraph internal[No public ingress]")
        for deployment in unrouted:
            lines.append(f'    {_node_id(deployment)}["{deployment}"]')
        lines.append("  end")

    lines += ["```", ""]

    if unrouted:
        lines += [
            "## Services with no public ingress",
            "",
            "Reachable only from inside the cluster — service-to-service traffic",
            "(ZeroMQ REQ/REP) or scheduled work.",
            "",
            *[f"- `{d}`" for d in unrouted],
            "",
        ]

    if chart.secrets:
        lines += [
            "## Secret templates",
            "",
            "Names only — the chart maps these into each deployment's environment.",
            "",
            *[f"- `{s}`" for s in chart.secrets],
            "",
        ]

    return "\n".join(lines)
